### ISSUE TITLE
Destination Modified Before Digipeat

### ISSUE THREAD

**Issue by na7q** [markqvist/MicroDigi#4]
Decided to pull out the homebrewed TNC for an upcoming project. I happened to notice this issue.
This packet below is the raw digipeated packet of the Arduino TNC with the call NA7Q-1. The packet was sent from my FT1XDR which sends in compressed beacons. Notice that it adds -9 to the DEST.
NA7Q-9>T6QPRT-9,NA7Q-1*:`3>5l <0x1c>[/`_$<0x0d>

Here is another packet in which it was digipeated by the Arduino TNC. This packet was not compressed, and seems to digipeat fine.
NA7Q>APX204,NA7Q-1*:=4610.24N/12334.25W#PHG7280KNAPPA Digi & IGate

So my assumption is that compressed beacons don't properly format.

**Comment by markqvist** [comment]
Thanks for reporting this, I'll look into it!

**Comment by na7q** [comment]
Excellent! Hopefully it's not just me being a doof. But I don't think so haha.

**Comment by dl1mx** [comment]
Corrected with pull request #5 
SRC SSID was set instead of DST

**Comment by na7q** [comment]
Thank you!!

**Comment by markqvist** [comment]
Considering this fixed by dl1mx. Thanks for the patch!
